apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-service-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NguyenvanHaissh/argo-manifests.git
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-apps 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
